version: "2"
services:
  scw-creator:
    build:
      context: .
    image: bee42/scw-docker-machine-creator
    privileged: true
    ports:
      - 22
    volumes:
      - "./data:/data"
    environment:
     - SCALEWAY_TOKEN
     - SCALEWAY_ORGANIZATION
     - SCALEWAY_REGION
